site_name: Nick's Digital Garden
theme:
  name: material
  language: ko  # 한국어 검색 지원
  features: []      

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - extra.css
